### ISSUE TITLE
Get the app posting to an appropriate bundle/operino at platform.code4health.org

### ISSUE THREAD

**Issue by davekilroy** [AppertaFoundation/Diadem#107]
currently the app posts data to Jay's Operino / bundle because I was not able to get it to successfully post to my Operino /bundle - so something is wonky!

**Comment by ColinSloane** [comment]
Rob Dyke to be invited to GitHub and assigned to this issue

**Comment by ColinSloane** [comment]
Closed by Dave and Colin post github review
