### ISSUE TITLE
[IG] Add a new screen after the Declaration screen (including logic) to use "Declaration of Consent"

### ISSUE THREAD

**Issue by davekilroy** [AppertaFoundation/Diadem#108]
These two screens may involve changes to the openEHR template - need to liaise with Ian McNicoll...

Need to add some GUI (and logic) to help the assessor "make the 'Declaration of Consent' available" in some form to patient / informant / care home - e.g. link to website/email/print to local printer

**Comment by ColinSloane** [comment]
Links to #116
