### ISSUE TITLE
Delete previously saved assessments at appropriate time

### ISSUE THREAD

**Issue by davekilroy** [AppertaFoundation/Diadem#110]
[ ] on successfully posting to openEHR (and delete any outstanding reminder ids)
[ ] on opening the app if the time-limit has expired

**Comment by davekilroy** [comment]
for testing purposed I've set the limit to 10 minutes, after which, when the app launches it will delete out-of-date assessment files on the device as well as the relevant parts of the preferences array/file (which incorporates a manifest of all saved assessments)

**Comment by davekilroy** [comment]
I've now added code such that it should no longer be possible to access assessments that have gone out of date whilst a user is logged in (and other 'edge' use cases)

**Comment by ColinSloane** [comment]
Closed by Dave and Colin post github review
