### ISSUE TITLE
It should not be possible for users to enter non nhs.net emails as report receivers in the frontend 

### ISSUE THREAD

**Issue by jaykola** [AppertaFoundation/Diadem#12]
- [x] reject non-nhs.net email adresses for DiADeM Recipient roles at diademauth.code4health.org
- [x] improve the rejection message a user sees when attempting to use a non-nhs.net email

At this point, all reports generated by Diadem contain patient identifiable data. So sending reports from Diadem should be restricted to nhs.net email domain only

**Comment by Apperta** [comment]
Dave to refine error message
