### ISSUE TITLE
On diademauth, set minimum standards for passwords (currently any 8 chars will suffice)

### ISSUE THREAD

**Issue by davekilroy** [AppertaFoundation/Diadem#143]
-  [x] passwords much have min 8 and max 20 characters long
- [x] passwords much have at least 1 lower-case character
- [x] passwords much have at least 1 upper-case character
- [x] passwords much have at least 1 number
- [x] passwords much have at least one special character (e.g. punctuation character)
- [x] max 5 failed login attempts after which an enforced wait period of 15 minutes
- [x] changes to the app so it works with all of the above when in online mode
- [x] new functionality in the app to replicate most of the above when in offline mode

**Comment by davekilroy** [comment]
This email from Roland gives more information (although some of the criteria in the policy will need discussing for our purposes):


Dave

In answer to our discussion this morning on passwords, we need the passwords to be compliant with the example policy at this link. 
In particular:

Can we ensure that ANY alphanumerics are allowed - the list they provided is not a limiting list.
The password on the app itself should not "simplify" the password - at the present moment the app does not distinguish between lower and upper case.
I would ideally like to have some mechanism on the system that checks the strength of the password.
Alan - this password policy will need to be included in the Apperta Security policy.
Thanks

Roland

**Comment by ColinSloane** [comment]
Closed by Dave and Colin post github review
