### ISSUE TITLE
Amend the DiADem PDF Report to show new data

### ISSUE THREAD

**Issue by davekilroy** [AppertaFoundation/Diadem#146]
- [x] in the app, add assessor email and organisation name
- [x] in the app, refer to assessor instead of interviewer
- [x] in the app, implement new format as suggested by Roland
- [ ] on the server, recreate Jay's 'receiving' script and amend if needed for the new format

**Comment by davekilroy** [comment]
link to Roland's document https://docs.google.com/spreadsheets/d/1K66Dv7ljmu0S3fEvHtMOql-vZW5fxPBvlglq_3jfWX8/edit?ts=5a730885#gid=0

**Comment by ColinSloane** [comment]
Hi Dave/Rob
I wonder if we can also show in the report confirmation of the lassesor 'informing the patient' as per the 'Making the patient aware' screen
Then showing how consent was obtained which will be a simple Yes - or if No(does the patient have capacity and has refused?)  if No  (Has a best interest decision been made) Yes

**Comment by ColinSloane** [comment]
Closed Dave and Colin 13/08/2018
