### ISSUE TITLE
Amend ‘consent’ text to new version from Roland

### ISSUE THREAD

**Issue by davekilroy** [AppertaFoundation/Diadem#154]

**Comment by davekilroy** [comment]
Text amended, I have also changed the choices available in the 'Patient Consent' screen as per Roland's change - and as a result have made a comment on Roland's document suggesting that he 'Patient Consent' screen should focus on 'Patient Capacity' and have an extra screen focusing on 'Consent - Patient DOES Have Capacity'

**Comment by ColinSloane** [comment]
Closed Dave and Colin 13/08/2018
