### ISSUE TITLE
For improved security, where the hardware supports it, use secureKey for an extra layer of encryption

### ISSUE THREAD

**Issue by davekilroy** [AppertaFoundation/Diadem#158]
The SecureKey library provides a way to use the 'keychain' operated by the Android, iOS and MacOS operating systems. This means each individual installation of the app on machines running these operating systems can have their own randomly set and unique password (unique both to the particular device the app might be installed on - i.e. no other device will have this password - and unique to the app - i.e. no other app on the device will have this password, or be able to access the password or enclosing secureKey.

This means we can have an additional inner layer of encryption for DiADeM's data which should pass very stringent security checks. 

Please note that older versions* of Android, iOS and macOS are not able to run a modern keychain and in these situations DiADeM will continue using its already very strong encryption without attempting to apply a secureKey layer of encryption or decryption.

SecureKey works on iOS 10 (released September 2016) and above, Android 8 (released August 2017) and above, and macOS Sierra (released September 2016) and above.

Currently Windows machines do not run a keychain and it is not possible to use SecureKey encryption with these machines.

**Comment by ColinSloane** [comment]
Closed Dave and Colin 13/08/2018
