### ISSUE TITLE
Augment the "inform, capacity and consent" section of the app

### ISSUE THREAD

**Issue by davekilroy** [AppertaFoundation/Diadem#159]
Builds upon, and is related to issue "Amend ‘consent’ text to new version from Roland" #154 - in particular add a screen and display a clear order from inform through to capacity and then consent to the user:

- inform patient - all users
- patient capacity - all users
- if the patient has capacity, the next screen will be about getting (or not getting) their consent
- if the patient does not have capacity, the next screen will be about 'best interest' consent

**Comment by davekilroy** [comment]
slight changes as follows to the text in Roland's document:

- first screen titled "Inform the Patient:
- next screen titled "Patient Capacity"
- if patient has capacity next screen titled "Consent: Patient Has Capacity"
- if patient does not have capacity next screen titled "Consent: Patient Does Not Have Capacity"

the text of the new screen titled "Consent: Patient Has Capacity" has been changed to that of the "Consent: Patient Does Not Have Capacity" screen with only relevant parts changed

**Comment by ColinSloane** [comment]
Closed Dave and Colin 13/08/2018
