### ISSUE TITLE
[bug] the new secureKey encryption method is being applied to older iOS devices that can't handle it

### ISSUE THREAD

**Issue by davekilroy** [AppertaFoundation/Diadem#165]
Hildi reported this bug on her iPad2 running iOS 9.3.5 (the app should not have tried to use secureKey on anything less than 10.0.0)

**Comment by davekilroy** [comment]
tested on Dave's iPhone4s (haven't heard back from Hildi's iPad2, but I believe it's fixed there too)

**Comment by ColinSloane** [comment]
Closed Dave and Colin 13/08/2018
