### ISSUE TITLE
Dealing with 'patient-not-known' (stage 1) - add a link to send an email directly to the Clinician, they then have to complete the assessment again

### ISSUE THREAD

**Issue by ColinSloane** [AppertaFoundation/Diadem#17]
Agree. This can be included in the body of the email. Or we can do it server side. Probably easier to include in body of email via app.

**Comment by Apperta** [comment]
Need to investigate a 'reject' report status when sent to wrong practice

**Comment by ApplicationInsight** [comment]
It is not a good idea for the DiADeM Recipient to be able to email the 'Clinician Undertaking a DiADeM Assessment' directly for a number of reasons - better if the Recipient clicks a link in the email which notifies the system and then sends the Clinician an email (which would include the CompostionId)

@ApplicationInsight & @jaykola to liaise on how this happens

**Comment by jaykola** [comment]
For this to happen, there has to be an association stored between the 'reportSent' and the 'reportComposer'. Currently this association is maintained in two places (if I am not wrong):

- DiademAuth server @ApplicationInsight can add in the details
- Inidus Notification pipeline:

### Inidus Notification pipeline:
For auditing purposes, the pipeline maintains a record of 'who sent what to whom'. This means it is possible to include an 'id' of the relevant notification in the email. For example, we would include a 'footer' link like - 'Click<this link> if you think you should not have received this email. Where <link> would look like https://platform.code4health.org/notifications/{id}/report

This would trigger an automatic look up for the corresponding 'reportComposer' in the 'Notification' stored in the C4H notification pipeline. Using this info, the pipeline would send a 'report rejected' email - that would include the corresponding 'compositionId'. From here on, regular Diadem functionality would kick off, where 'recordComposer' views the assessment/composition in the app and edits it (new functionality??).
