### ISSUE TITLE
Cant post saved assesments in Test CDR mode

### ISSUE THREAD

**Issue by ColinSloane** [AppertaFoundation/Diadem#171]

**Comment by ColinSloane** [comment]
This is when an assessor saves a partly done assessment and goes back to complete it - the completed assessment will not post to the CDR for some reason

**Comment by davekilroy** [comment]
Actually I think that I was wrong and that we COULD return to a previously saved assessment and post it successfully

What was a bug was trying to create a new assessment from the 'Saved Assessment' screen (i.e. trying to create a new assessment when there were some previously saved assessments). When this happened in 1.0.1 and he or she had any previously saved assessment then every new assessment made would not post successfully and the user had to delete all previously saved assessments in order to post an assessment (except for the first saved assessment - that one, created in the usual way and not from the 'Saved Assessments' screen posted just fine...)

**Comment by ColinSloane** [comment]
Gret stuff Dave - lets give it a test when the new version goes on the app store

**Comment by davekilroy** [comment]
Hi Colin, just to check - are you saying I should put a version 1.0.2 without you or the others testing?

Kind regards

Dave Kilroy 

 <http://applicationinsight.com/>

Application Insight 

Web: www.applicationinsight.com <http://www.applicationinsight.com/>
Email: dave@applicationinsight.com <mailto:dave@applicationinsight.com>
Twitter: @App_Insight_ <https://twitter.com/App_Insight_>
Tel: (01752) 671 418 

Application Insight Ltd is a company registered in England (no: 05761203) Registered Office: 22 Hartley Park Gardens, Plymouth PL3 5HU http://www.applicationinsight.com The contents and any attachments of this electronic mail message are confidential and intended only for the named addressees. Dissemination, forwarding, publication or other use of the message or attachments by any unauthorised person is strictly prohibited. Unless stated to the contrary, any opinions expressed in this message are personal and may not be attributed to Application Insight Ltd.

**Comment by ColinSloane** [comment]
Hi Dave

Is it possible for us to test before it goes on the app store?

BW

Colin

**Comment by davekilroy** [comment]
Of course

“...So, I’m hoping to be able to upload a 1.0.2 version for you to test by close-of-play tomorrow at the latest with all four issues done"


And I was assuming, though perhaps I should have said explicitly, that I wouldn’t submit it to the app store without your agreement

Kind regards

Dave Kilroy 

 <http://applicationinsight.com/>

Application Insight 

Web: www.applicationinsight.com <http://www.applicationinsight.com/>
Email: dave@applicationinsight.com <mailto:dave@applicationinsight.com>
Twitter: @App_Insight_ <https://twitter.com/App_Insight_>
Tel: (01752) 671 418 

Application Insight Ltd is a company registered in England (no: 05761203) Registered Office: 22 Hartley Park Gardens, Plymouth PL3 5HU http://www.applicationinsight.com The contents and any attachments of this electronic mail message are confidential and intended only for the named addressees. Dissemination, forwarding, publication or other use of the message or attachments by any unauthorised person is strictly prohibited. Unless stated to the contrary, any opinions expressed in this message are personal and may not be attributed to Application Insight Ltd.

**Comment by ColinSloane** [comment]
Closed Dave and Colin 13/08/2018
