### ISSUE TITLE
DiADeM Android app asks for access to local media and files 

### ISSUE THREAD

**Issue by jaykola** [AppertaFoundation/Diadem#18]
Is there a reason why DiADeM is asking to access local files?

**Comment by ApplicationInsight** [comment]
no I don't this is needed (in terms of Android) as the app only needs to access files within it's 'sandbox' on the device

**Comment by jaykola** [comment]
Maybe the permissions that were specified during app registration have to
be reviewed.

**Comment by ApplicationInsight** [comment]
yes quite - shall we discuss more on Thursday? Especially how we progress issues, team norms, and degrees of verbosity?

**Comment by jaykola** [comment]
Okay ☺️

**Comment by ApplicationInsight** [comment]
- [ ] change authorisations in the app's Android build settings
