### ISSUE TITLE
Better Code4Health branding in the app

### ISSUE THREAD

**Issue by davekilroy** [AppertaFoundation/Diadem#26]
- [x] create a sized range of PNG images of logo
- [x] import font used in logo text
- [x] incorporate these assets in the splash screen and the app
- [ ] create LiveCode-readable SVG colour images of logo
- [ ] create LiveCode-readable SVB colour images of logo text
- [ ] incorporate these assets in the splash screen and the app

**Comment by Fishy1976** [comment]
Branding fine
