### ISSUE TITLE
Users can store part-completed compositions locally on the device

### ISSUE THREAD

**Issue by ApplicationInsight** [AppertaFoundation/Diadem#27]
- [x] set up basic   encrypted save of composition data
- [x] set up local manifest system for encrypted files
- [x] set up system to manage retrieval and loading of encrypted files
- [x] set up GUI to choose & load encrypted  files

**Comment by ColinSloane** [comment]
Internet connection not available - need to have local saving feature until such a time when
you can back on to the internet. (feedback  from testing - re iterates Dave's Issue)

**Comment by ColinSloane** [comment]
Hi Dave 
Just wondering if you made any progress with this issue - local storing of assessment when no internet connection available?

**Comment by ApplicationInsight** [comment]
Hi Colin - no not yet - but this issue (together with issue  #24) are my next tasks!
