### ISSUE TITLE
User can login and use the app when offline (stage 1)

### ISSUE THREAD

**Issue by davekilroy** [AppertaFoundation/Diadem#28]
- [x] set up encrypted  storage of login credentials
- [x] set up GUI informing user when connection is not available and a choice to proceed or not
- [x] set up and/or modify existing GUI for offline usage (i.e. for ehrid, NHS Choices)
- [x] link in with the encrypted storage feature at #27

**Comment by Apperta** [comment]
It would be preferable to not force the user to log in each time and check terms and conditions each time

**Comment by Apperta** [comment]
Link to #27

**Comment by rappel1** [comment]
This should be high priority as it is a requirement for initial release of the app

**Comment by Fishy1976** [comment]
Working IOA and Android
