### ISSUE TITLE
Login with email address

### ISSUE THREAD

**Issue by ColinSloane** [AppertaFoundation/Diadem#33]
Login free text box to have labels
1)  Email address
2) Password

**Comment by ColinSloane** [comment]
Just tested this on IPhone 6 and cant see where the labels appear 'Email' and 'Password' ?
I assume they appear when first using the App and then the email field is populated by memory but the password box remains blank (should it contain the label 'Password' everytime?

**Comment by ApplicationInsight** [comment]
As regards the email field - yes before you add your email for the first time (and before the app saves it) you will see "email" in the email field.

The password field is slightly trickier, if I put "password" in there until the user enters their password, it would currently show as a series of dots (standard for a password field). I'll make a custom field that will allow "password" to appear as plain text but with obscures everything else.

I'm removing the 'done' label on this issue

**Comment by ApplicationInsight** [comment]
I was able to make a fix for iOS because I can access the 'font' attribute of a native field in LiveCode for iOS - however I can't do the same on Android so will have to carry out some 'fakery' to achieve the same or similar result
