### ISSUE TITLE
Choose recipient drop down to include 'save to device' option

### ISSUE THREAD

**Issue by ColinSloane** [AppertaFoundation/Diadem#37]
Choose recipient- if not there, can it be skipped? I had to select one of the recipients to get to next page. Can you skip if you don't want to upload to recipient?

**Comment by ColinSloane** [comment]
possibly an option to 'save to device'? This would be helpful also when no internet connection is available?

**Comment by Apperta** [comment]
'Save for later' added to all screens

**Comment by Apperta** [comment]
Link to #27
