### ISSUE TITLE
Reports general clean up make better

### ISSUE THREAD

**Issue by ColinSloane** [AppertaFoundation/Diadem#39]
In the reports where dementia is not indicated, I would suggest changing the wording from:
"There is no need to add this patient to the GP Register using the ICD 10 code(s)."
 to 
"There is no need to add this patient to your GP practice dementia register." 

In the reports where dementia IS indicated, we're using the wrong coding terminology - it's not ICD10 codes that will be used (they're used in hospitals), it's CTV3/Read Codes:

 "Please add this patient to the GP Register using the ICD 10 code(s) taken from the North Guidance on Dementia and Delirium Coding document published July 2014." I think we also need to change, "Or using the regionally, locally agreed ICD 10 codes in your area please also consider adding other codes highlighted in the report which help to indicate location of patient and blood test declined."
to:
 "Using the appropriate QOF codes please record whether the appropriate blood tests -
routine haematology, biochemistry tests (including electrolytes, calcium, glucose, and renal and liver function), thyroid function tests, serum vitamin B12 and folate levels - have been carried out or record where these blood tests have been declined or excepted." (Need to check this wording with Sara) 

Also suggest changing the next paragraph to: "Ensure that planned follow-up and next steps are recorded in the patient's health record including any
onward referrals where appropriate. Ensure that arrangements are made with the patient
and carer (where applicable) to jointly review the care plan."

**Comment by ColinSloane** [comment]
Already started to work through much of this and have already produced some template reports
[6CIT FalsediademReport (1).pdf](https://github.com/AppertaFoundation/Diadem/files/1194743/6CIT.FalsediademReport.1.pdf)
[bloodna6citdiademReport (3).pdf](https://github.com/AppertaFoundation/Diadem/files/1194745/bloodna6citdiademReport.3.pdf)
[bloodnavailable6citdiademReport (2).pdf](https://github.com/AppertaFoundation/Diadem/files/1194747/bloodnavailable6citdiademReport.2.pdf)
[nursinghome6CITdiademReport (4).pdf](https://github.com/AppertaFoundation/Diadem/files/1194744/nursinghome6CITdiademReport.4.pdf)
[Reportgpcog1and2.pdf](https://github.com/AppertaFoundation/Diadem/files/1194746/Reportgpcog1and2.pdf)




 to reflect the changes needed

**Comment by Apperta** [comment]
@ApplicationInsight - add EMIS Web Read code to relevant reports

**Comment by Apperta** [comment]
@ColinSloane revisit report colouring as this will require additional dev work and prioritisation

**Comment by ColinSloane** [comment]
Reports now revisited and removed colour backgrounds
[Reportgpcog1and2.pdf](https://github.com/AppertaFoundation/Diadem/files/1240059/Reportgpcog1and2.pdf)
[bloodnavailable6citdiademReport (2).pdf](https://github.com/AppertaFoundation/Diadem/files/1240060/bloodnavailable6citdiademReport.2.pdf)
[nursinghome6CITdiademReport (4).pdf](https://github.com/AppertaFoundation/Diadem/files/1240061/nursinghome6CITdiademReport.4.pdf)
[6CIT FalsediademReport (1).pdf](https://github.com/AppertaFoundation/Diadem/files/1240063/6CIT.FalsediademReport.1.pdf)
[bloodna6citdiademReport (3).pdf](https://github.com/AppertaFoundation/Diadem/files/1240062/bloodna6citdiademReport.3.pdf)

**Comment by ApplicationInsight** [comment]
- [ ] New Read (EMIS Web) location code added, extra wording added to both locations codes and displayed in the location type field
- [ ] 6CIT and GPCOG scores shown in shortened format
- [ ] SystemOne and EMIS Web codes added to text if dementia is not indicated
- [ ] DiADeM SNOMED CT code added to text whether dementia is indicated or not
- [ ] "Please check before confirming diagnosis of dementia" text is shown in capital (I am unable to make any formatting changes on the DiADeM report)
- [ ] The 'North Guidance on Dementia...' link now resolves to the correct URL
