### ISSUE TITLE
Date of Birth field must be mandatory and should not have a default value

### ISSUE THREAD

**Issue by ColinSloane** [AppertaFoundation/Diadem#41]
date of birth - should this be mandatory? I skipped this and it worked
need a way of confirming date of birth so no automatic move on

**Comment by Apperta** [comment]
Blank default? - mandatory field/do not skip

**Comment by ApplicationInsight** [comment]
The _"date-of-birth value must be mandatory and should not have a default value"_  tasklist item in issue #22 also covers this issue
