### ISSUE TITLE
The Numbering of the DiADeM Criteria should match in the Paper version and the App version

### ISSUE THREAD

**Issue by ColinSloane** [AppertaFoundation/Diadem#45]
The logical way to go through the DiADeM tool is from 1 to 5.  However, in the App version the pathway goes 2 first then 1,3,4,5.  Are we able to bring the two in line so its much less confusing?
Options
1) Functional Impairment appears as the first 'criteria' in the App
2) Change Functional Impairment to no. 2 and Cognitive Impairment to no. 1 in the paper version and the App.

**Comment by ColinSloane** [comment]
Have contacted Sara and Penny both feel you cant change the order of the paper version.  its embedded in too many places already for example has been used for 2 years now by some GP's and we have shared across the Country with other Clinical Networks like Buckinghamshire, Leicester, and others.  Also templates in Bradford SystmOne and Leicester EMIS Web mirror the paper versions order 1 to 5.  Both agree the two should be the same and suggest we pull in the Functional Impairment (No.1) as the first test in the App.  Dave - how difficult will that be?? Is this doable by Public Beta launch? Discuss!!  We need a fairly speedy answer to this - I will need to alter the user guides to suit before they can feature in the App

**Comment by ApplicationInsight** [comment]
Colin, hopefully it won't be a big job - actually swapping round the screens is dead easy, it's just checking and testing logic that'll involve a bit more time. However it would be better not to show it to public until we have this sorted out so I'll commit to getting it done before the 6th - and ideally for the internal testing on the 21st

**Comment by ColinSloane** [comment]
Great Thanks for that Dave - I will begin to update the user guides and let you and Alan (website) have them once complete
By the way I also upload documents to GitHub as well as sharing by e-mail.  Im sure everyone realises we can do that :+1: )

**Comment by ApplicationInsight** [comment]
Reviewed ordering in general (especially when going backwards if a user was reviewing his/her responses)

An area we have had problems with in the past was moving backwards from 'DiADeM 1 - Functional Impairment' - this will now be 'DiADeM 3 - Corroborating History'

If 6CIT is in use the display order of screens will be:

- Going forward ...6CIT Q6 - 6CIT Summary - Informant Screen - Corroborating History...
- Going back ...Corroborating History - Informant Screen - 6CIT Summary - 6CIT Q6... 

If GPCOG (part 1, not part 2) is in use the display order of screens will be:

- Going forward ...GPCOG (part1) Q5 - GPCOG (part 1) Summary - Informant Screen - Corroborating History...
- Going back ...Corroborating History - Informant Screen - GPCOG (part1) Summary - GPCOG (part1) Q5... 

If GPCOG (part 1 & 2) is in use the display order of screens will be:

Going forward
- ...
- GPCOG (part1) Q5 
- GPCOG (part 1) Summary 
- Informant Screen 
- GPCOG (part 2) Q1 
- ... 
- GPCOG (part 2) Q6 
- GPCOG (part 2) Summary 
- Corroborating History
- ...

Going back:
- ...
- Corroborating History
- GPCOG (part 2) Summary 
- GPCOG (part 2) Q6
- ...
- GPCOG (part 2) Q1 
- Informant Screen 
- GPCOG (part 1) Summary 
- GPCOG (part1) Q5
- ...


 ...Corroborating History - GPCOG (part 2) Summary - GPCOG (part 2) Q6 ... GPCOG (part 2)

Informant Screen - GPCOG (part1) Summary - GPCOG (part1) Q5...
