### ISSUE TITLE
Write a security statement for DiADeM App

### ISSUE THREAD

**Issue by ColinSloane** [AppertaFoundation/Diadem#49]
Jay to write a statement and produce a flow chart to demonstrate thr safe storage of patient identifiable information

**Comment by ColinSloane** [comment]
Just updating this issue.  Apologies I rushed it when I first posted it and would like to describe it a bit better now I have thought about it a bit more.

Jay with some input from Dave  to write a statement and produce a flow chart to demonstrate the safe storage of patient identifiable information.  To include a description of the encryption used on by the App when storing on the device and a description of the safe storage of the data once it is sent from the App to the server (Operon? Inidus? ????) and then onwards to the report recipient via an nhs.net email account If this can be done for the 21st Aug we can test it out with colleagues who have raised concerns in the past (Buckinghamshire) to set minds at ease and for our own comfort that we are operating as 'safely' as we can be.   I am happy to also run it by our Yorkshire and Humber region IG Lead and  Caldecott Guardian just for further reassurances for when we launch the Public Beta version

**Comment by ColinSloane** [comment]
Just adding this discussion we had by email - better that all discussions are recorded on GitHub too

Just following our Skype call this morning (Me, Dave and Alan) and the only thing I wanted to just remind you ahead of your leave was about the security statement issue #49 on GitHub
The timeline for this is 21st Aug and I was hoping to run it by a few people once it’s done (give it the Anne test from Buckinghamshire etc) other than that everything seems to be on course

Jay Replied
21st August is doable for this security statement. I just discussed this at our Inidus team meeting. So I'll have something for review by 21st.

**Comment by ApplicationInsight** [comment]
Thanks Colin - I'll create a new issue to remind me...
