### ISSUE TITLE
Ensure the Android version is as performant as the iOS version

### ISSUE THREAD

**Issue by davekilroy** [AppertaFoundation/Diadem#59]
- [x] bad date formatting from date picker in the 'Patient' screen
- [x] unable to query the demographics service due to bad date format
- [x] date picker sometimes appears already open when entering the 'Patient' screen
- [x] a selected date appears with the year in two digit form (i.e. "03")
- [x] revisiting a previously populated date picker shows the date beginning with "20"
- [x] the 'firstName' field & associated assets in the 'Patient' screen sometimes are not visible after ending an edit
- [x] the 'Login' button in the 'Login' screen sometimes remains 'greyed-out' when it should be blue (although it still does work)
- [x] 'flash' of input fields on leaving some screens
- [x] 'flash' of input fields on closing the slide-up menu
- [x] on returning to the app, if a partly-completed diadem session was left from the previous session the app returns to the same screen (i.e. it does not force the user to login again) - perhaps the solution is to offer to save progress up to the current screen and then kick the user out so they have to login again and then choose the partly-completed composition (if they wish)

**Comment by ColinSloane** [comment]
Just to feed back that I have tried the android version on my HUDL I deleted the original and downloaded the new version.  Now when you touch on the DiADeM app icon nothing happens??  After a while an error message pops up saying DiADeM isn't responding - Do you want to close it? Wait/Report/OK

**Comment by ApplicationInsight** [comment]
A new issue #60 has been opened to address @ColinSloane 's comment above

**Comment by Fishy1976** [comment]
No difference in performance - working
