### ISSUE TITLE
Manage display of all text on small screen devices

### ISSUE THREAD

**Issue by davekilroy** [AppertaFoundation/Diadem#83]
- [x] small text in the 2nd review screen after the primary review screen
- [x] small text in all three 'consent' screens

**Comment by davekilroy** [comment]
tested on iPhone 5 and text was miniature properly

Have yet to test on a smaller Nexus 4...

Edit: tested on Nexus4 and it's OK

**Comment by davekilroy** [comment]
This is the second 'review' screen the assessor sees at the end of an assessment that indicates impairment - as seen (magnified) on a Samsung Galaxy S7 - with reduced text size and no scroll review screen 2 - no scroll - galaxys7
![review screen 2 - no scroll - galaxys7](https://user-images.githubusercontent.com/4001277/35874935-b991cb34-0b65-11e8-8856-229aac7c6768.png)

This is the second 'review' screen the assessor sees at the end of an assessment that indicates impairment - as seen (magnified) on a Samsung Galaxy S7 - with unreduced text size and scrolling text
![review screen 2 - scrolling - galaxys7](https://user-images.githubusercontent.com/4001277/35874947-c8996164-0b65-11e8-8577-d2a0b9ab9864.png)


This is the second 'review' screen the assessor sees at the end of an assessment that indicates impairment - as seen (magnified) on an iPhone 5 - with reduced text size and no scroll
![review screen 2 - no scroll - iphone5](https://user-images.githubusercontent.com/4001277/35874971-dc069f00-0b65-11e8-89a4-a50cf9c2e607.png)

This is the second 'review' screen the assessor sees at the end of an assessment that indicates impairment - as seen (magnified) on an iPhone5 - with unreduced text size and scrolling text
![review screen 2 - scrolling - iphone5](https://user-images.githubusercontent.com/4001277/35874996-ef352808-0b65-11e8-9ff6-8494d7cfff46.png)

**Comment by Fishy1976** [comment]
Suggested change of font on Android - wouldn't worry too much though it is legible

**Comment by ColinSloane** [comment]
Closed by Dave and Colin post github review

**Comment by ColinSloane** [comment]
Closed by Dave and Colin post github review
