### ISSUE TITLE
Improve the behaviour of the login screen (especially when the on-screen keyboard is visible)

### ISSUE THREAD

**Issue by davekilroy** [AppertaFoundation/Diadem#85]

**Comment by davekilroy** [comment]
This is the second 'review' screen the assessor sees at the end of an assessment that indicates impairment - as seen (magnified) on a Samsung Galaxy S7 - with reduced text size and no scroll review screen 2 - no scroll - galaxys7
![review screen 2 - no scroll - galaxys7](https://user-images.githubusercontent.com/4001277/35874657-08ddf9c0-0b65-11e8-9d07-df0363ec1c70.png)

This is the second 'review' screen the assessor sees at the end of an assessment that indicates impairment - as seen (magnified) on a Samsung Galaxy S7 - with unreduced text size and scrolling text
![review screen 2 - scrolling - galaxys7](https://user-images.githubusercontent.com/4001277/35874701-260b67ee-0b65-11e8-9e01-f87929af81ee.png)

**Comment by Fishy1976** [comment]
works ok IOS and Android
